spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/books
    username: root
    password: Sanjay@987321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
